"""add defects table

Revision ID: 7542ad2b5433
Revises: 21fa843789ad
Create Date: 2026-08-11 16:01:01.813737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7542ad2b5433'
down_revision: Union[str, Sequence[str], None] = '21fa843789ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='所属任务 ID'),
    sa.Column('defect_type', sa.String(length=100), nullable=False, comment='缺陷类型'),
    sa.Column('component', sa.String(length=200), nullable=True, comment='部件'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='位置'),
    sa.Column('length', sa.Float(), nullable=True, comment='长度(mm)'),
    sa.Column('depth', sa.Float(), nullable=True, comment='深度(mm)'),
    sa.Column('unit', sa.String(length=10), nullable=True, comment='单位'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='数量'),
    sa.Column('wall_thickness', sa.Float(), nullable=True, comment='设计壁厚(mm)'),
    sa.Column('original_text', sa.Text(), nullable=False, comment='原始文本'),
    sa.Column('severity', sa.Integer(), nullable=True, comment='严重度 S'),
    sa.Column('occurrence', sa.Integer(), nullable=True, comment='发生度 O'),
    sa.Column('detection', sa.Integer(), nullable=True, comment='检测度 D'),
    sa.Column('rpn', sa.Integer(), nullable=True, comment='风险优先数 RPN'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级: 低/中/高/严重'),
    sa.Column('level', sa.Integer(), nullable=True, comment='风险等级数字'),
    sa.Column('reasons', sa.JSON(), nullable=True, comment='触发原因列表(字符串数组)'),
    sa.Column('suggestion', sa.Text(), nullable=True, comment='改进建议'),
    sa.Column('standard_ref', sa.String(length=500), nullable=True, comment='引用标准编号'),
    sa.Column('triggered_rules', sa.JSON(), nullable=True, comment='触发的规则列表'),
    sa.Column('law_references', sa.JSON(), nullable=True, comment='法规引用列表'),
    sa.Column('mandatory_measures', sa.JSON(), nullable=True, comment='强制措施列表'),
    sa.Column('inspection_advice', sa.JSON(), nullable=True, comment='检验建议列表'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='其他扩展数据（可放自定义字段）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defects_task_id'))
        batch_op.drop_index(batch_op.f('ix_defects_id'))

    op.drop_table('defects')
    # ### end Alembic commands ###
